### ISSUE TITLE
Mosek error

### ISSUE THREAD

**Issue by kibaekkim** [wzhangw/ComplexBC#2] opened 2020-10-22 14:18 UTC
The Mosek version I am using is:
```
MOSEK Version 9.2.28 (Build date: 2020-10-20 09:05:51)
Copyright (c) MOSEK ApS, Denmark. WWW: mosek.com
Platform: MACOSX/64-X86
```

When running the example, I am getting this:
```
ERROR: Mosek.MosekError(3915, "There is no barx available for the solution type 2.")
```

**Comment by wzhangw** [comment] 2020-10-22 14:30
Can you try again after adding the Ipopt dependency?

**Comment by kibaekkim** [comment] 2020-10-22 14:49
The issue was found even after adding `ipopt`. Here is the whole message:

```
julia> ComplexBC.main("examples/pglib_opf_case3_lmbd.m")
[info | PowerModels]: removing 3 cost terms from generator 3: Float64[]
[info | PowerModels]: removing 3 cost terms from generator 3: Float64[]

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

[ Info: Tree nodes: processed 0, left 1, total 1, best bound -Inf, best incumbent 5812.642939909429
ERROR: Mosek.MosekError(3915, "There is no barx available for the solution type 2.")
Stacktrace:
 [1] getbarxj(::Mosek.Task, ::Mosek.Soltype, ::Int32) at /Users/kibaekkim/.julia/packages/Mosek/6LuE3/src/msk_functions.jl:2087
 [2] getbarxj at /Users/kibaekkim/.julia/packages/Mosek/6LuE3/src/msk_functions.jl:2077 [inlined]
 [3] matrix_solution(::MosekTools.MosekModel, ::Mosek.Soltype) at /Users/kibaekkim/.julia/packages/MosekTools/sppJY/src/MosekTools.jl:268
 [4] optimize!(::MosekTools.MosekModel) at /Users/kibaekkim/.julia/packages/MosekTools/sppJY/src/MosekTools.jl:275
 [5] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekTools.MosekModel}) at /Users/kibaekkim/.julia/packages/MathOptInterface/k7UUH/src/Bridges/bridge_optimizer.jl:264
 [6] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /Users/kibaekkim/.julia/packages/MathOptInterface/k7UUH/src/Utilities/cachingoptimizer.jl:215
 [7] optimize!(::JuMP.Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/kibaekkim/.julia/packages/JuMP/qhoVb/src/optimizer_interface.jl:130
 [8] optimize! at /Users/kibaekkim/.julia/packages/JuMP/qhoVb/src/optimizer_interface.jl:106 [inlined] (repeats 2 times)
 [9] bound!(::BranchAndBound.JuMPNode{ComplexBC.SpatialBCBranch}) at /Users/kibaekkim/Documents/REPOS/ComplexBC/src/bb_exts.jl:183
 [10] run(::BranchAndBound.AbstractTree) at /Users/kibaekkim/.julia/packages/BranchAndBound/3BJq5/src/tree.jl:19
 [11] macro expansion at ./timing.jl:174 [inlined]
 [12] main(::String) at /Users/kibaekkim/Documents/REPOS/ComplexBC/src/ComplexBC.jl:34
 [13] top-level scope at REPL[2]:1
```

**Comment by wzhangw** [comment] 2020-10-26 02:19
It seems that this problem can be resolved by adding `MOI.SLOW_PROGRESS` to the array of acceptable termination statuses in `DualDecomposition`. Maybe we should add some termination status flexibility there.

**Comment by kibaekkim** [comment] 2020-10-26 13:25
can you add it to `DualDecomposition` and make a PR?

**Comment by wzhangw** [comment] 2020-10-26 16:42
Correction: the problem is actually solved by re-set the `Mosek` optimizer for the model, which is added in commit https://github.com/wzhangw/ComplexBC/commit/d638334633be288e816ee92b019ea057fc9f14b4

**Comment by kibaekkim** [comment] 2020-10-29 13:37
I still get the error. Any idea?

**Comment by wzhangw** [comment] 2020-11-01 05:23
It seems that the error is reproduced if `MosekTools` of version 0.9.4 is used. The example runs with `MosekTools` 0.9.3. Somehow with 0.9.4 `Mosek` treats the solution of our model as an integer solution (according to `solutiondef` function from `Mosek.jl`) while the model is SDP. For now I fix the dependency of `MosekTools` at version 0.9.3 in commit https://github.com/wzhangw/ComplexBC/commit/02fb1304303fae7b3a99a1e303c9fc0fe98fb94b. An issue might need to be raised to `MosekTools`, but I am having difficulty coming up with a smaller case that reproduces this error.

**Comment by kibaekkim** [comment] 2020-11-02 20:07
Yes, it is running with the `MosekTools` version 0.9.3.

**Closed as completed** 2020-11-02 20:09 UTC
